#!/usr/bin/env bash
#This is just checking the existence of the file


if [ -e ./school ]; then
	echo "school file exists"
	if [ ! -s ./school ]; then echo "school file is empty" ; else echo "school file is not empty"; fi
	if [ -f ./school ]; then echo "school is regular file"; fi
else  echo "school file does not exist"

fi	
