#!/usr/bin/env bash
#this is just a script


while read -r row
do
	var=$( echo "$row" | tr ":" " " )
	n=1
	us=""
	for i in $var
	do
		if [[ "$n" -eq 1 ]]; then us="$us$i"
		elif [[ "$n" -eq 3 ]] || [[ "$n" -eq 7 ]]; then us="$us:$i"; fi
		((n=n+1))
	done
	echo "$us"
done < /etc/passwd	

