#!/usr/bin/env bash 
#Trump loves Zelenski

sudo touch /var/run/myscript.pid &
echo $! > /var/run/myscript.pid

handle_term ( ) {
       echo 'I hate the kill command'
       sudo  rm -rf  /var/run/myscript.pid
       exit 0
}

handle_quit ( ) {
	sudo rm -rf //var/run/myscript.pid
       exit 0	


}



trap "echo 'Y U no love me?' " SIGINT
trap "handle_term" SIGTERM
trap "handle_quit " SIGQUIT

while true; do
	 echo "To infinity and beyond"
	sleep 2
done


